version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    container_name: zookeeper
    networks:
      my-network:
        ipv4_address: 172.20.0.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"
  clickhouse01:
    image: clickhouse/clickhouse-server:23.7
    hostname: clickhouse01
    container_name: clickhouse01
    ports:
      - 9001:9000
      - 8124:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.2
    extra_hosts:
      - "clickhouse02:172.20.0.3"
      - "clickhouse03:172.20.0.4"
    depends_on:
      - zookeeper
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
  clickhouse02:
    image: clickhouse/clickhouse-server:23.7
    hostname: clickhouse02
    container_name: clickhouse02
    ports:
      - 9002:9000
      - 8125:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.3
    extra_hosts:
      - "clickhouse01:172.20.0.2"
      - "clickhouse03:172.20.0.4"
    depends_on:
      - zookeeper
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
  clickhouse03:
    image: clickhouse/clickhouse-server:23.7
    hostname: clickhouse03
    container_name: clickhouse03
    ports:
      - 9003:9000
      - 8126:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.4
    extra_hosts:
      - "clickhouse01:172.20.0.2"
      - "clickhouse02:172.20.0.3"
    depends_on:
      - zookeeper
    volumes:
      - ./config3.xml:/etc/clickhouse-server/config.xml
  clickhouse04:
    image: clickhouse/clickhouse-server:23.6
    hostname: clickhouse04
    container_name: clickhouse04
    ports:
      - 9004:9000
      - 8127:8123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      my-network:
        ipv4_address: 172.20.0.5
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
